version: '2'

services:
  ci_agent:
    build:
      context: ./ci_agent_dev
    volumes:
      - "docker-socket-vol:/var/run/docker/"
  dcp:
    build:
      context: .
    command: /sockguard -filename /var/run/docker/sockguard.sock -set-cgroup-parent this-container
    cgroup_parent: test-cgroup
    volumes:
      - "docker-socket-vol:/var/run/docker/"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  docker-socket-vol:
