# This file validates how you might use sockguard as a sidecar container to some CI worker/agent,
# including the (non-trivial) socket volume mapping. This is required due to the chicken-and-egg
# of creating the socket before the volume otherwise.

version: '2'

services:
  ci_agent:
    build:
      context: ./ci_agent_dev
    volumes:
      - "docker-socket-vol:/var/run/docker/"
  sockguard:
    build:
      context: ../../
      dockerfile: ./examples/cgroup_parent/Dockerfile
    command: -filename /var/run/docker/sockguard.sock -cgroup-parent this-container
    cgroup_parent: test-cgroup
    volumes:
      - "docker-socket-vol:/var/run/docker/"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  docker-socket-vol:
